// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const username = "backsideHungary@gmail.com"
const password = "$FC5SnS!EdQtHKF"
describe('8verify_toggle_showhide_pw', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('8verify_toggle_showhide_pw', async function() {
    await driver.get("https://www.instagram.com/")
    await driver.manage().window().setRect({ width: 1650, height: 900 })
    await driver.wait(until.elementLocated(By.css('[name="username"]')), 10000);
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys(username)
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys(password)
    await driver.findElement(By.xpath("//*[@id=\"loginForm\"]//button[contains(.,\"Log in\")]")).click()
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//button[@type=\"button\" and contains(.,\"Show\")]"))),30000)
    await driver.findElement(By.xpath("//button[@type=\"button\" and contains(.,\"Show\")]")).click()
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//button[@type=\"button\" and contains(.,\"Hide\")]"))),30000)
    await driver.findElement(By.xpath("//button[@type=\"button\" and contains(.,\"Hide\")]")).click()
  })
})
